using System.Linq;
using System.Numerics;
using Content.Client.Shuttles.Systems;
using Content.Shared._NF.Shuttles.Components;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Shuttles.Components;
using Content.Shared.Shuttles.Systems;
using Content.Shared.Shuttles.UI.MapObjects;
using Content.Shared.Timing;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Audio;
using Robust.Shared.Audio.Systems;
using Robust.Shared.Map;
using Robust.Shared.Map.Components;
using Robust.Shared.Physics.Components;
using Robust.Shared.Player;
using Robust.Shared.Random;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class CrewScreen : BoxContainer
{
    [Dependency] private readonly IEntityManager _entManager = default!;

    public Action<EmployeeOptions>? toggleEmployeeClicked;
    public bool HasID = false;
    
    public CrewScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        switchCrew.OnPressed += _ => toggleEmployeeClicked?.Invoke(EmployeeOptions.Crew);
        switchPilot.OnPressed += _ => toggleEmployeeClicked?.Invoke(EmployeeOptions.Pilot);
        switchCaptain.OnPressed += _ => toggleEmployeeClicked?.Invoke(EmployeeOptions.Captain);

        OnVisibilityChanged += OnVisChange;
    }

    public void UpdateState(CrewInterfaceState state)
    {
        if (state.hasId)
        {
            targetIdButton.Text = state.IdName;
            if (state.isCaptain)
                switchCaptain.Text = "Demote from Captain";
            else
                switchCaptain.Text = "Promote to Captain";
            if (state.isPilot)
                switchPilot.Text = "Demote from Pilot";
            else
                switchPilot.Text = "Promote to Pilot";
            if (state.isCrew)
                switchCrew.Text = "Demote from Crew";
            else
                switchCrew.Text = "Promote to Crew";

        }

        else
        {
            targetIdButton.Text = "Insert Employee ID";
            switchCrew.Text = "Waiting for ID";
            switchCaptain.Text = "Waiting for ID";
            switchPilot.Text = "Waiting for ID";
        }

        
    }



    private void OnVisChange(Control obj)
    {
        if (!obj.Visible)
            return;

    }

}
