using System.Numerics;
using Content.Shared.Crescent.Radar;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.Input;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Map;
using Robust.Shared.Physics.Components;
using Content.Shared.NamedModules.Components;
using Content.Shared.Chemistry;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class NavScreen : BoxContainer
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    private SharedTransformSystem _xformSystem;

    public Action? OnGroup1Pressed;
    public Action? OnGroup2Pressed;
    public Action? OnGroup3Pressed;
    public Action? OnGroup4Pressed;
    public Action? OnGroup5Pressed;
    public Action<List<string>>? OnRename;

    private EntityUid? _shuttleEntity;

    public EntityUid? Console;

    private Dictionary<int, Button> _buttons = new();
    private Dictionary<int, LineEdit> _editable = new();

    public bool RenameModeToggle = false;

    

    public NavScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _xformSystem = _entManager.System<SharedTransformSystem>();

        IFFToggle.OnToggled += OnIFFTogglePressed;
        IFFToggle.Pressed = NavRadar.ShowIFF;

        IFFShuttleToggle.OnToggled += OnIFFShuttleTogglePressed;
        IFFShuttleToggle.Pressed = NavRadar.ShowIFFShuttles;

        DockToggle.OnToggled += OnDockTogglePressed;
        DockToggle.Pressed = NavRadar.ShowDocks;

        Group1.OnPressed += OG1P;
        Group2.OnPressed += OG2P;
        Group3.OnPressed += OG3P;
        Group4.OnPressed += OG4P;
        Group5.OnPressed += OG5P;

        _buttons[1] = Group1;
        _buttons[2] = Group2;
        _buttons[3] = Group3;
        _buttons[4] = Group4;
        _buttons[5] = Group5;


        foreach(var (index, button) in _buttons)
        {
            var specialUi = new LineEdit();
            if(button.Text is not null)
                specialUi.Text = button.Text;
            _editable[index] = specialUi;
        }

        RenameButton.OnPressed += RenamePressed;

        // Frontier - IFF search
        IffSearchCriteria.OnTextChanged += args => OnIffSearchChanged(args.Text);
    }

    public void ButtonsToReadyState()
    {
        UpdateButtonNames();
        ButtonHolder.RemoveAllChildren();
        foreach (var (index, button) in _buttons)
        {
            ButtonHolder.AddChild(button);
        }
        
    }

    public void ButtonsToEditState()
    {
        UpdateButtonNames();
        ButtonHolder.RemoveAllChildren();
        foreach (var (index, line) in _editable)
            ButtonHolder.AddChild(line);
    }

    public void UpdateButtonNames()
    {
        if (Console is not null & _entManager.TryGetComponent<NamedModulesComponent>(Console, out var namesComp) && namesComp is not null)
        {
            foreach (var (index, button) in _buttons)
            {
                button.Text = namesComp.ButtonNames[index-1];
                _editable[index].Text = namesComp.ButtonNames[index-1];
            }
        }
    }

    private void UpdateComponentNames(List<string> newNames)
    {
        if (Console is not null & _entManager.TryGetComponent<NamedModulesComponent>(Console, out var namesComp) &&
            namesComp is not null)
            namesComp.ButtonNames = newNames;
    }

    private void OG1P(BaseButton.ButtonEventArgs args)
    {
        OnGroup1Pressed?.Invoke();
    }

    private void OG2P(BaseButton.ButtonEventArgs args)
    {
        OnGroup2Pressed?.Invoke();
    }

    private void OG3P(BaseButton.ButtonEventArgs args)
    {
        OnGroup3Pressed?.Invoke();
    }

    private void OG4P(BaseButton.ButtonEventArgs args)
    {
        OnGroup4Pressed?.Invoke();
    }

    private void OG5P(BaseButton.ButtonEventArgs args)
    {
        OnGroup5Pressed?.Invoke();
    }

    private void RenamePressed(BaseButton.ButtonEventArgs args)
    {
        RenameModeToggle = !RenameModeToggle;
        if (RenameModeToggle)
            ButtonsToEditState();
        else
        {
            List<string> newNames = new();
            foreach(var (index, lineedit) in _editable)
            {
                newNames.Add(lineedit.Text);
            }
            UpdateComponentNames(newNames);
            OnRename?.Invoke(newNames);
            ButtonsToReadyState();
        }
    }

    public void SetConsole(EntityUid console)
    {
        Console = console;
        if (Console is null)
            return;
        if(_entManager.TryGetComponent<NamedModulesComponent>(Console, out var moduleComp))
        {
            foreach(var (index, button) in _buttons)
            {
                button.Text = moduleComp.ButtonNames[index-1];
            }
        }
    }


    // Frontier - IFF search
    private void OnIffSearchChanged(string text)
    {
        text = text.Trim();

        NavRadar.IFFFilter = text.Length == 0
            ? null // If empty, do not filter
            : (entity, grid, iff) => // Otherwise use simple search criteria
            {
                _entManager.TryGetComponent<MetaDataComponent>(entity, out var metadata);
                return metadata != null && metadata.EntityName.Contains(text, StringComparison.OrdinalIgnoreCase);
            };
    }

    public void SetShuttle(EntityUid? shuttle)
    {
        _shuttleEntity = shuttle;

        // Frontier - PR #1284 Add Shuttle Designation
        if (_entManager.TryGetComponent<MetaDataComponent>(shuttle, out var metadata))
        {
            var shipNameParts = metadata.EntityName.Split(' ');
            var designation = shipNameParts[^1];
            if (designation[2] == '-')
            {
                NavDisplayLabel.Text = string.Join(' ', shipNameParts[..^1]);
                ShuttleDesignation.Text = designation;
            }
            else
                NavDisplayLabel.Text = metadata.EntityName;
        }
        // End Frontier - PR #1284
    }

    private void OnIFFTogglePressed(BaseButton.ButtonEventArgs args)
    {
        NavRadar.ShowIFF ^= true;
        args.Button.Pressed = NavRadar.ShowIFF;
    }

    private void OnIFFShuttleTogglePressed(BaseButton.ButtonEventArgs args)
    {
        NavRadar.ShowIFFShuttles ^= true;
        args.Button.Pressed = NavRadar.ShowIFFShuttles;
    }

    private void OnDockTogglePressed(BaseButton.ButtonEventArgs args)
    {
        NavRadar.ShowDocks ^= true;
        args.Button.Pressed = NavRadar.ShowDocks;
    }

    public void UpdateState(NavInterfaceState scc)
    {
        NavRadar.UpdateState(scc);
    }

    public void UpdateState(IFFInterfaceState iffState)
    {
        NavRadar.UpdateState(iffState);
    }

    public void SetMatrix(EntityCoordinates? coordinates, Angle? angle)
    {
        _shuttleEntity = coordinates?.EntityId;
        NavRadar.SetMatrix(coordinates, angle);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        if (!_entManager.TryGetComponent(_shuttleEntity, out TransformComponent? gridXform) ||
            !_entManager.TryGetComponent(_shuttleEntity, out PhysicsComponent? gridBody))
        {
            return;
        }

        var (_, worldRot, worldMatrix) = _xformSystem.GetWorldPositionRotationMatrix(gridXform);
        var worldPos = Vector2.Transform(gridBody.LocalCenter, worldMatrix);

        // Get the positive reduced angle.
        var displayRot = -worldRot.Reduced();

        GridPosition.Text = $"{worldPos.X:0.0}, {worldPos.Y:0.0}";
        GridOrientation.Text = $"{displayRot.Degrees:0.0}";

        var gridVelocity = gridBody.LinearVelocity;
        gridVelocity = displayRot.RotateVec(gridVelocity);
        // Get linear velocity relative to the console entity
        GridLinearVelocity.Text = $"{gridVelocity.X + 10f * float.Epsilon:0.0}, {gridVelocity.Y + 10f * float.Epsilon:0.0}";
        GridAngularVelocity.Text = $"{-gridBody.AngularVelocity + 10f * float.Epsilon:0.0}";
    }
}
