using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared.Shuttles.BUIStates;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class RadarConsoleWindow : FancyWindow,
    IComputerWindow<NavInterfaceState>
{
    private bool _updatedOnce;

    public RadarConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(NavBoundUserInterfaceState cState)
    {
        if (_updatedOnce)
        {
            if (cState.DirtyFlags == NavBoundUserInterfaceState.StateDirtyFlags.IFF)
            {
                RadarScreen.UpdateState(cState.IFFState);
                return;
            }
        }
        else
        {
            _updatedOnce = true;
        }

        RadarScreen.UpdateState(cState.State);
        RadarScreen.UpdateState(cState.IFFState);
    }
}
