using System.Buffers;
using System.Numerics;
using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Shuttles.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class ShuttleConsoleWindow : FancyWindow,
    IComputerWindow<ShuttleBoundUserInterfaceState>
{
    [Dependency] private readonly IEntityManager _entManager = default!;

    private ShuttleConsoleMode _mode = ShuttleConsoleMode.Nav;

    public event Action<MapCoordinates, Angle>? RequestFTL;
    public event Action<NetEntity, Angle>? RequestBeaconFTL;

    public event Action<NetEntity, NetEntity>? DockRequest;
    public event Action<NetEntity>? UndockRequest;

    public event Action<string>? idSlotButtonPressed;

    public event Action<bool>? crewHudVisChange;

    public event Action<EmployeeOptions>? employToggleButtonClicked;

    public Action? OnGroup1Pressed;
    public Action? OnGroup2Pressed;
    public Action? OnGroup3Pressed;
    public Action? OnGroup4Pressed;
    public Action? OnGroup5Pressed;
    public Action<List<string>>? OnRename;

    private bool _updatedOnce;


    public ShuttleConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // Mode switching
        NavModeButton.OnPressed += NavPressed;
        MapModeButton.OnPressed += MapPressed;
        DockModeButton.OnPressed += DockPressed;
        CrewManagementButton.OnPressed += CrewPressed;

        // Modes are exclusive
        var group = new ButtonGroup();

        NavModeButton.Group = group;
        MapModeButton.Group = group;
        DockModeButton.Group = group;
        CrewManagementButton.Group = group;

        NavModeButton.Pressed = true;
        SetupMode(_mode);

        MapContainer.RequestFTL += (coords, angle) =>
        {
            RequestFTL?.Invoke(coords, angle);
        };

        MapContainer.RequestBeaconFTL += (ent, angle) =>
        {
            RequestBeaconFTL?.Invoke(ent, angle);
        };

        DockContainer.DockRequest += (entity, netEntity) =>
        {
            DockRequest?.Invoke(entity, netEntity);
        };

        DockContainer.UndockRequest += entity =>
        {
            UndockRequest?.Invoke(entity);
        };
        CrewContainer.targetIdButton.OnPressed += _ => idSlotButtonPressed?.Invoke(SharedShuttleConsoleComponent.IdSlotName);
        CrewContainer.OnVisibilityChanged += control => crewHudVisChange?.Invoke(control.Visible);
        CrewContainer.toggleEmployeeClicked += _ => employToggleButtonClicked?.Invoke(_);
        NavContainer.OnGroup1Pressed += () => OnGroup1Pressed?.Invoke();
        NavContainer.OnGroup2Pressed += () => OnGroup2Pressed?.Invoke();
        NavContainer.OnGroup3Pressed += () => OnGroup3Pressed?.Invoke();
        NavContainer.OnGroup4Pressed += () => OnGroup4Pressed?.Invoke();
        NavContainer.OnGroup5Pressed += () => OnGroup5Pressed?.Invoke();
        NavContainer.OnRename += args => OnRename?.Invoke(args);
    }


    private void ClearModes(ShuttleConsoleMode mode)
    {
        if (mode != ShuttleConsoleMode.Nav)
        {
            NavContainer.Visible = false;
        }

        if (mode != ShuttleConsoleMode.Map)
        {
            MapContainer.Visible = false;
            MapContainer.SetMap(MapId.Nullspace, Vector2.Zero);
        }

        if (mode != ShuttleConsoleMode.Dock)
        {
            DockContainer.Visible = false;
        }

        if (mode != ShuttleConsoleMode.Crew)
        {
            if (CrewContainer.HasID)
            {
                idSlotButtonPressed?.Invoke(SharedShuttleConsoleComponent.IdSlotName);
                CrewContainer.HasID = false;
            }

            CrewContainer.Visible = false;

        }
    }

    private void NavPressed(BaseButton.ButtonEventArgs obj)
    {
        SwitchMode(ShuttleConsoleMode.Nav);
    }

    private void MapPressed(BaseButton.ButtonEventArgs obj)
    {
        SwitchMode(ShuttleConsoleMode.Map);
    }

    private void DockPressed(BaseButton.ButtonEventArgs obj)
    {
        SwitchMode(ShuttleConsoleMode.Dock);
    }

    private void CrewPressed(BaseButton.ButtonEventArgs obj)
    {
        SwitchMode(ShuttleConsoleMode.Crew);
    }


    private void SetupMode(ShuttleConsoleMode mode)
    {
        switch (mode)
        {
            case ShuttleConsoleMode.Nav:
                NavContainer.Visible = true;
                break;
            case ShuttleConsoleMode.Map:
                MapContainer.Visible = true;
                MapContainer.Startup();
                break;
            case ShuttleConsoleMode.Dock:
                DockContainer.Visible = true;
                break;
            case ShuttleConsoleMode.Crew:
                CrewContainer.Visible = true;
                break;
            default:
                throw new NotImplementedException();
        }
    }

    public void SwitchMode(ShuttleConsoleMode mode)
    {
        if (_mode == mode)
            return;

        _mode = mode;
        ClearModes(mode);
        SetupMode(_mode);
    }

    public enum ShuttleConsoleMode : byte
    {
        Nav,
        Map,
        Dock,
        Crew,
    }

    public void UpdateState(EntityUid owner, ShuttleBoundUserInterfaceState cState)
    {
        if (_updatedOnce)
        {
            if (cState.DirtyFlags == ShuttleBoundUserInterfaceState.StateDirtyFlags.IFF)
            {
                NavContainer.UpdateState(cState.IFFState);
                return;
            }
        }
        else
        {
            _updatedOnce = true;
        }

        var coordinates = _entManager.GetCoordinates(cState.NavState.Coordinates);
        NavContainer.SetShuttle(coordinates?.EntityId);
        NavContainer.SetConsole(owner);
        MapContainer.SetShuttle(coordinates?.EntityId);
        MapContainer.SetConsole(owner);

        CrewContainer.UpdateState(cState.CrewState);
        NavContainer.UpdateState(cState.NavState);
        MapContainer.UpdateState(cState.MapState);
        DockContainer.UpdateState(coordinates?.EntityId, cState.DockState);
    }
}
