- type: job
  id: HunterSRM
  name: job-name-hunter
  description: job-description-hunter
  playTimeTracker: JobHunterSRM
  weight: 22
  startingGear: HunterGear
  alwaysUseSpawner: true
  icon: "JobIconHunter"
  requireAdminNotify: false
  supervisors: job-supervisors-imperial 
  canBeAntag: false
  access:
  - Command
  - Hunter
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier

- type: startingGear
  id: HunterGear
  equipment:
    id: HunterPDA
    ears: ClothingHeadsetHunter
    jumpsuit: ClothingUniformJumpsuitHunter
    head: ClothingHeadHatHunter
    shoes: ClothingShoesBootsHunter
    outerClothing: ClothingOuterArmorHunterDuster
    gloves: ClothingHandsGlovesHunter