using Content.Client.Computer;
using Content.Client.UserInterface.Controls;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.PointCannons;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Content.Client.Shuttles.UI;
using Robust.Client.UserInterface.Controls;
using System.Linq;

namespace Content.Client.PointCannons;

[GenerateTypedNameReferences]
public sealed partial class TargetingConsoleWindow : FancyWindow, IComputerWindow<ShuttleBoundUserInterfaceState>
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    public ShuttleNavControl Radar => NavRadar;
    public Action<string>? OnCannonGroupChange;

    public TargetingConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        NavRadar.ControlledTurrets = [];
    }

    public void UpdateState(TargetingConsoleBoundUserInterfaceState state, TargetingConsoleComponent console)
    {
        if (state.NavState != null && state.IFFState != null)
        {
            NavRadar.UpdateState(state.NavState);
            NavRadar.UpdateState(state.IFFState);
        }

        UpdateGroupSelector(console);
    }

    public void UpdateGroupSelector(TargetingConsoleComponent console)
    {
        CannonGroupSelectorBox.DisposeAllChildren();

        foreach (string groupName in console.CannonGroups.Keys.ToList())
        {
            Button groupButton = new();
            groupButton.Text = string.Concat(char.ToUpper(groupName[0]), groupName.Substring(1)); //capitalized name
            groupButton.OnPressed += (_) =>
            {
                OnCannonGroupChange?.Invoke(groupName);
                console.CurrentGroupName = groupName;
                NavRadar.ControlledTurrets = console.CurrentGroup;
            };
            CannonGroupSelectorBox.AddChild(groupButton);
        }
    }
}
