
- type: faction
  name: "Divine Sol Mandate"
  id: DSM
  description: |
    Controlling much of human space outside the Crescent, the Divine Sol Mandate, or simply
    'the Empire' to laymen, are a product of early space-era corporate classism and
    post-exploration boom-feudalism, ruled by the mysticized, allegedly all-powerful 'Kaiser' from
    the Prime system within the Imperial Core constellation, formerly known to archivists as Sol and
    Pisces, respectively. After the uprising of the NCWL, the Empire had found themselves diminished,
    but a succesful counter-attack managed to secure the starfortress Kal Suzerai
    and allowed for a return of Imperial forces to the area, altough control on the fringes of Taypan
    is still disputed, and raids or terror acts are common.
    
    Effectively the prime superpower of all of humanity, the Empire allows for a good amount of
    economic freedom for its subjects and promotes loyalty in a manner not too dissimilar to
    the megacorporations of old Earth, with aspiring members climbing up the noble ladder of
    different houses, such as House Olywir of the Domain system. Freeholders thinking that they
    can speak up against the current regime quickly find themselves screened against and
    detained, however, with tight information control preventing widespread dissent and
    often rewriting history itself to suit the needs of the Empire. Other races are permitted within Imperial
    ranks, but often subject to increased scrutiny and formal or informal discrimination
  color: "#9FED58"
  weight: 1
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: dsm

- type: faction
  name: "New Crescent Worker's League"
  id: NCWL
  description: |
    Currently the holder of many patents and technologies from the now-defunct NanoTrasen
    industries, SHI is the unmatched and unrivaled corporate powerhouse in the Sector.
    Fingers in every pie,they manage logistics between systems,development of new technologies,
    mining operations, and even dabble in the manufacturing of space-capable vessels.Sharing the
    system with the Syndicate, they have made their local headquarters at the Tatsumoto
    Shipworks, enjoying acc
  color: "#9FED58"
  weight: 0
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: ncwl


- type: faction
  name: "Taypan FreeStations Coalitions"
  id: TFSC
  description: department-Civilian-description
  color: "#9FED58"
  weight: -3
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: tfsc

- type: faction
  name: "Shinohara Heavy Industries"
  id: SHI
  description: department-Civilian-description
  color: "#9FED58"
  weight: -4
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: shi

- type: faction
  name: "Saint Romaine's Militia"
  id: SRM
  description: department-Civilian-description
  color: "#9FED58"
  weight: -5
  enabled: true
  icon:
    sprite: /Textures/_Crescent/faction_icons.rsi
    state: srm