- type: department
  id: Cargo
  description: department-Cargo-description
  color: "#A46106"
  weight: -90
  primary: false

- type: department
  id: Civilian
  description: department-Civilian-description
  color: "#9FED58"
  weight: -10
  roles:
  - Bartender
  - Borg
  - Botanist
  - Boxer
  - Chaplain
  - KadetNCWL
  - Chef
  - Clown
#  - HeadOfPersonnel
  - Lawyer
  - Librarian
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Visitor
  - Zookeeper
  - ServiceWorker
  - Contractor # Frontier
  - Mercenary # Frontier
  - Pilot # Frontier
  - Captain # Frontier
  - ChiefEngineer # Frontier
  - AtmosphericTechnician # Frontier
  - StationEngineer # Frontier
  - TechnicalAssistant # Frontier
  - ResearchDirector # Frontier
  - Scientist # Frontier
  - ResearchAssistant # Frontier
  - Quartermaster # Frontier
  - CargoTechnician # Frontier
  - SalvageSpecialist # Frontier
  enabled: false

- type: department
  id: Command
  description: department-Command-description
  color: "#334E6D"
  roles:
  - CentralCommandOfficial
  - KommissarNCWL
  - HeadOfPersonnel # Not shown but needed here for playtime
  - HeadOfSecurity # Not shown but needed here for playtime
#  - ChiefMedicalOfficer
  - StationRepresentative # Frontier
  - Sheriff  # Frontier
  - StationTrafficController # Frontier
  primary: false
  weight: 100
  enabled: false

- type: department
  id: Engineering
  description: department-Engineering-description
  color: "#EFB341"
  weight: -94
  primary: false

- type: department
  id: Medical
  description: department-Medical-description
  color: "#52B4E9"
  weight: -93
  primary: false

- type: department
  id: Security
  description: department-Security-description
  color: "#DE3A3A"
  weight: 20
  roles:
  - Detective # Frontier - No Longer Usable
  - HeadOfSecurity # Frontier - No Longer Usable
  - SecurityCadet # Frontier - No Longer Usable
  - SecurityOfficer # Frontier - No Longer Usable
  - Warden # Frontier - No Longer Usable
  - PrisonGuard ##nyano
  - Brigmedic # Frontier
#  - SecurityGuard # Frontier
  - DetectiveNF # Frontier
  - Cadet # Frontier
  - KadetNCWL
  - Deputy # Frontier
  - Bailiff # Frontier
  - Sheriff # Frontier
  - SeniorOfficer # Frontier
  enabled: false

- type: department
  id: Science
  description: department-Science-description
  color: "#D381C9"
  weight: -92
  primary: false

- type: department
  id: Specific
  description: department-Specific-description
  color: "#9FED58"
  weight: -91
  primary: false

- type: department
  id: Antag
  description: department-Security-description
  color: "#DE3A3A"
  weight: -11
  roles:
  - PirateCaptain
  - PirateFirstMate
  - Pirate
  - Prisoner ##nyano
  primary: false

- type: department
  id: NCWL
  description: department-NCWL-description
  color: "#FFD580"
  weight: 100
  roles:
  - AdministratorNCWL
  - KommissarNCWL
  - SanitarNCWL
  - ArtificerNCWL
  - DoktorNCWL
  - KapitanNCWL
  - KadetNCWL
  enabled: true

- type: department
  id: NCSP
  description: department-NCSP-description
  color: "#DC143C"
  weight: 90
  roles:
  - RingleaderNCSP
  - LieutenantNCSP
  - InfanteerNCSP
  - TechnicianNCSP
  - RipperdocNCSP
  - ChemcookNCSP
  - OperativeNCSP
  - IntelligenceOfficerNCSP
  - ForemanNCSP
  - ShipbreakerNCSP
  enabled: true

- type: department
  id: DSM
  description: department-DSM-description
  color: "#684871"
  weight: 85
  roles:
  - FreeholderDSM
  - LevymanDSM
  - KnightDSM
  - CourtierDSM
  - AdjutantDSM
  - GovernorDSM
  enabled: true

- type: department
  id: SRM
  description: department-SRM-description
  color: "#4a6741"
  weight: 80
  roles:
  - TenderSRM
  - AcolyteSRM
  - HunterSRM
  - MontagneSRM
  - OverseerSRM
  enabled: true