using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Crescent.Broadcaster.UI;

[GenerateTypedNameReferences]
public sealed partial class BroadcasterUI : FancyWindow
{
    public Action<int>? ClickBroadcast; 
    public int Amount;
    public BroadcasterUI()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("bank-atm-menu-title");
    }

}
