- type: entity
  id: StandardCrescentStation #Main faction stations
  parent:
    - BaseStation
    - BaseStationCargo
    - BaseStationJobsSpawning
    - BaseStationRecords
    - BaseStationShuttles
    - BaseStationAlertLevels
    - BaseStationSiliconLawCrescentStation
    - BaseStationEmpImmune
    - BaseStationSectorNews
    - BaseStationSpaceArtilleryImmune # Space artillery gets deleted. Not ideal, diegetic solution at some point please
    - BaseStationPreventPilot # Prevent piloting stations immune to space arty
  noSpawn: true
  components:
    - type: Transform

- type: entity
  id: StandardCrescentOutpost #POI
  parent:
    - BaseStation
    - BaseStationCargo
    - BaseStationJobsSpawning
    - BaseStationRecords
    - BaseStationShuttles
    - BaseStationAlertLevels
    - BaseStationSiliconLawCrescentStation
  noSpawn: true
  components:
    - type: Transform

- type: entity
  id: StandardCrescentVessel #Combat vessel
  parent:
    - BaseStation
    - BaseStationJobsSpawning
    - BaseStationRecords
    - BaseStationCargo
    - BaseCombatShipAlertLevels
    - BaseStationAllEventsEligible
    - BaseStationRenameFaxes
    - BaseStationRenameWarpPoints
    - BaseStationSiliconLawCrescentShips
  noSpawn: true
  components:
    - type: Transform

- type: entity
  id: StandardCrescentCivilianVessel #Civilian / unarmed vessel
  parent:
    - BaseStation
    - BaseStationJobsSpawning
    - BaseStationRecords
    - BaseStationAlertLevels
    - BaseStationAllEventsEligible
    - BaseStationRenameFaxes
    - BaseStationCargo
    - BaseStationRenameWarpPoints
    - BaseStationSiliconLawCrescentShips
  noSpawn: true
  components:
    - type: Transform

- type: entity
  id: StandardCrescentExpeditionVessel #Expeds
  parent:
    - BaseStation
    - BaseStationJobsSpawning
    - BaseStationRecords
    - BaseStationAlertLevels
    - BaseStationAllEventsEligible
    - BaseStationRenameFaxes
    - BaseStationCargo
    - BaseStationRenameWarpPoints
    - BaseStationSiliconLawCrescentShips
    - BaseStationExpeditions
  noSpawn: true
  components:
    - type: Transform

- type: entity
  id: BaseStationSiliconLawCrescentStation
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: NTDefault

- type: entity
  id: BaseStationSiliconLawCrescentShips
  abstract: true
  components:
  - type: SiliconLawProvider
    laws: Corporate

- type: entity
  id: BaseStationRenameFaxes
  abstract: true
  components:
    - type: StationRenameFaxes

- type: entity
  id: BaseStationRenameWarpPoints
  abstract: true
  components:
    - type: StationRenameWarps

- type: entity
  id: BaseStationEmpImmune
  abstract: true
  components:
    - type: StationEmpImmune

# Sector-wide news access, should be on stations with comms (radio station, telecomms)
- type: entity
  id: BaseStationSectorNews
  abstract: true
  components:
    - type: SectorNews

# Space artillery will not damage this station
- type: entity
  id: BaseStationSpaceArtilleryImmune
  abstract: true
  components:
    - type: BlockSpaceArtilleryProjectileGrid

- type: entity
  id: BaseCombatShipAlertLevels
  abstract: true
  components:
    - type: AlertLevel
      alertLevelPrototype: combatShipAlerts

- type: entity
  id: BaseStationPreventPilot
  abstract: true
  components:
    - type: PreventPilot
