name: CRLF Check

on:


jobs:
  build:
    name: CRLF Check
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.6.0
    - name: Check for CRLF
      run: Tools/check_crlf.py
